INSERT INTO activite VALUES (101,"Aéromodélisme");
INSERT INTO activite VALUES (201,"Formule racer / Vol à moteur / Voltige aérienne/Rallye aérien/Pilotage précision");
INSERT INTO activite VALUES (301,"Aérostation");
INSERT INTO activite VALUES (401,"Aikido / Aikibudo / Budo");
INSERT INTO activite VALUES (501,"Saut");
INSERT INTO activite VALUES (502,"Lancer");
INSERT INTO activite VALUES (503,"Course sur piste");
INSERT INTO activite VALUES (504,"Cross country");
INSERT INTO activite VALUES (505,"Course et marche sur route (hors stade)");
INSERT INTO activite VALUES (506,"Marche");
INSERT INTO activite VALUES (601,"Aviron");
INSERT INTO activite VALUES (701,"Badminton, Jeu de volant");
INSERT INTO activite VALUES (801,"Baseball");
INSERT INTO activite VALUES (802,"Softball");
INSERT INTO activite VALUES (803,"Cricket");
INSERT INTO activite VALUES (899,"Baseball (Autres)");
INSERT INTO activite VALUES (901,"Ballon au poing");
INSERT INTO activite VALUES (999,"Ballon au poing (Autres)");
INSERT INTO activite VALUES (1001,"Fosse universelle");
INSERT INTO activite VALUES (1002,"Parcours de chasse");
INSERT INTO activite VALUES (1003,"Fosse européenne");
INSERT INTO activite VALUES (1004,"Compak sporting");
INSERT INTO activite VALUES (1101,"Basket-Ball");
INSERT INTO activite VALUES (1201,"Billard (Français (carambole),Snooker,Anglais,Américain)");
INSERT INTO activite VALUES (1301,"Bowling");
INSERT INTO activite VALUES (1302,"Sports de quilles");
INSERT INTO activite VALUES (1401,"Boxe Anglaise");
INSERT INTO activite VALUES (1501,"Boxe Américaine");
INSERT INTO activite VALUES (1701,"Canoë de randonnée");
INSERT INTO activite VALUES (1702,"Course en ligne");
INSERT INTO activite VALUES (1703,"Descente");
INSERT INTO activite VALUES (1704,"Kayak-polo");
INSERT INTO activite VALUES (1705,"Slalom");
INSERT INTO activite VALUES (1706,"Raft (embarcation gonflable)");
INSERT INTO activite VALUES (1708,"Wave-ski");
INSERT INTO activite VALUES (1709,"Pirogue polynésienne (Va'a)/Pirogue dragon");
INSERT INTO activite VALUES (1710,"Kayak de mer");
INSERT INTO activite VALUES (1711,"Rodéo/Freestyle");
INSERT INTO activite VALUES (1712,"Merathon (océan racing)");
INSERT INTO activite VALUES (1713,"Marathon");
INSERT INTO activite VALUES (1801,"Char à voile (Aéroplage)");
INSERT INTO activite VALUES (1802,"Voilier des sables");
INSERT INTO activite VALUES (1803,"Char a cerf volant/à glace/à neige/ Kart à voile");
INSERT INTO activite VALUES (1901,"Course camarguaise");
INSERT INTO activite VALUES (2001,"Course d'orientation - Vtt");
INSERT INTO activite VALUES (2002,"Course d'orientation - Pédestre");
INSERT INTO activite VALUES (2003,"Course d'orientation - Ski");
INSERT INTO activite VALUES (2099,"Course d'orientation (Autres)");
INSERT INTO activite VALUES (2101,"Course landaise");
INSERT INTO activite VALUES (2201,"Cyclocross");
INSERT INTO activite VALUES (2202,"Bicross (BMX)");
INSERT INTO activite VALUES (2203,"Cyclisme sur piste");
INSERT INTO activite VALUES (2204,"Vtt (Cross Country/ Descente/ Trial/ Rallye/ Four Cross) / Vélo trial");
INSERT INTO activite VALUES (2205,"Polo-vélo");
INSERT INTO activite VALUES (2206,"Cyclisme en salle");
INSERT INTO activite VALUES (2208,"Freestyle");
INSERT INTO activite VALUES (2299,"Cyclisme (Autres)");
INSERT INTO activite VALUES (2301,"Cyclotourisme");
INSERT INTO activite VALUES (2401,"Danses par Couple (Danses de compétition)");
INSERT INTO activite VALUES (2402,"Autres Danses");
INSERT INTO activite VALUES (2499,"Danse (Autres)");
INSERT INTO activite VALUES (2501,"Echecs");
INSERT INTO activite VALUES (2601,"Equitation");
INSERT INTO activite VALUES (2602,"Concours complet");
INSERT INTO activite VALUES (2603,"Dressage");
INSERT INTO activite VALUES (2604,"Saut d'obstacle");
INSERT INTO activite VALUES (2605,"Attelage");
INSERT INTO activite VALUES (2606,"Horse - Ball");
INSERT INTO activite VALUES (2607,"Polo");
INSERT INTO activite VALUES (2608,"Randonnée équestre");
INSERT INTO activite VALUES (2609,"Course sur le plat");
INSERT INTO activite VALUES (2610,"Equitation western / Equitation camarguaise");
INSERT INTO activite VALUES (2611,"Raid équestre d'endurance");
INSERT INTO activite VALUES (2701,"Escrime (Epée / Fleuret / Sabre )");
INSERT INTO activite VALUES (2801,"Hockey subaquatique");
INSERT INTO activite VALUES (2802,"Pêche sous marine");
INSERT INTO activite VALUES (2803,"Nage avec palmes");
INSERT INTO activite VALUES (2804,"Plongée subaquatique (Plongée libre)");
INSERT INTO activite VALUES (2805,"Orientation subaquatique");
INSERT INTO activite VALUES (2806,"Plongée en apnée");
INSERT INTO activite VALUES (2807,"Plongée d'exploration / Photographie subaquatique");
INSERT INTO activite VALUES (2808,"Tir sur cible subaquatique");
INSERT INTO activite VALUES (2809,"Nage en eau vive");
INSERT INTO activite VALUES (2901,"Football / Football en salle (Futsal)");
INSERT INTO activite VALUES (3001,"Football Américain / Flag");
INSERT INTO activite VALUES (3101,"Full contact (boxe américaine)/Light contact/First full/Full défense/Super fight/Semi-contact");
INSERT INTO activite VALUES (3201,"Giraviation");
INSERT INTO activite VALUES (3301,"Golf");
INSERT INTO activite VALUES (3302,"Swing");
INSERT INTO activite VALUES (3303,"Crocket");
INSERT INTO activite VALUES (3401,"Gymnastique Artistique");
INSERT INTO activite VALUES (3402,"Gymnastique Rythmique");
INSERT INTO activite VALUES (3403,"Gymnastique Aérobic");
INSERT INTO activite VALUES (3404,"Expression gymnique");
INSERT INTO activite VALUES (3405,"Trampoline / Double mini-tramp");
INSERT INTO activite VALUES (3407,"Tumbling");
INSERT INTO activite VALUES (3408,"Gymnastique Acrobatique");
INSERT INTO activite VALUES (3501,"Gymnastique volontaire");
INSERT INTO activite VALUES (3601,"Haltérophilie / Force athlétique");
INSERT INTO activite VALUES (3602,"Musculation");
INSERT INTO activite VALUES (3603,"Culturisme");
INSERT INTO activite VALUES (3701,"Handball / Mini hand / Handball de plage");
INSERT INTO activite VALUES (3801,"Hockey en salle / Hockey sur gazon");
INSERT INTO activite VALUES (3901,"Javelot Tir sur cible");
INSERT INTO activite VALUES (4001,"Balle au tambourin");
INSERT INTO activite VALUES (4101,"Jeu de Paume");
INSERT INTO activite VALUES (4201,"Joutes et sauvetage nautique");
INSERT INTO activite VALUES (4301,"Judo / Jujitsu / Taïso");
INSERT INTO activite VALUES (4302,"Kendo / Iaïdo / Naginata / Jodo / Sport chanbara");
INSERT INTO activite VALUES (4303,"Sumo");
INSERT INTO activite VALUES (4401,"Karaté/Karaté jutsu/Goshin jutsu/Kobudo/Nihon Tai-jutsu/Taijitsu/Nambudo/Ninjutsu/Nunchaku/...");
INSERT INTO activite VALUES (4501,"Kick boxing / Cardio KB / Kick boxing light / KB Défense");
INSERT INTO activite VALUES (4601,"Longue paume");
INSERT INTO activite VALUES (4701,"Lutte traditionnelle / olympique libre / olympique gréco-romaine /  bretonne / féminine");
INSERT INTO activite VALUES (4702,"Sambo");
INSERT INTO activite VALUES (4801,"Canyonisme");
INSERT INTO activite VALUES (4802,"Escalade");
INSERT INTO activite VALUES (4803,"Raquette à neige");
INSERT INTO activite VALUES (4804,"Ski alpinisme");
INSERT INTO activite VALUES (4805,"Escalade sur Via ferrata/Corda");
INSERT INTO activite VALUES (4901,"Motocyclisme (course sur route ou sur piste)");
INSERT INTO activite VALUES (4902,"Moto verte");
INSERT INTO activite VALUES (4903,"Motocross / Enduro");
INSERT INTO activite VALUES (4904,"Motoball");
INSERT INTO activite VALUES (4905,"Quad");
INSERT INTO activite VALUES (4906,"Trial");
INSERT INTO activite VALUES (5001,"Motonautisme / Jet hydrojet / Aéroglisseur");
INSERT INTO activite VALUES (5002,"Modèle réduit");
INSERT INTO activite VALUES (5101,"Boxe thaïlandaise Muay Thaï");
INSERT INTO activite VALUES (5201,"Natation course sportive");
INSERT INTO activite VALUES (5202,"Natation synchronisée");
INSERT INTO activite VALUES (5203,"Natation en eau libre");
INSERT INTO activite VALUES (5204,"Plongeon");
INSERT INTO activite VALUES (5205,"Water-Polo");
INSERT INTO activite VALUES (5206,"Baignade loisirs");
INSERT INTO activite VALUES (5208,"Aquagym");
INSERT INTO activite VALUES (5301,"Padel");
INSERT INTO activite VALUES (5401,"Parachutisme");
INSERT INTO activite VALUES (5402,"Précision à l'atterrissage");
INSERT INTO activite VALUES (5403,"Parachutisme Vol relatif");
INSERT INTO activite VALUES (5404,"Parachutisme Voile contact");
INSERT INTO activite VALUES (5405,"Parachutisme Voltige");
INSERT INTO activite VALUES (5406,"Parachutisme Surf");
INSERT INTO activite VALUES (5407,"Expression libre");
INSERT INTO activite VALUES (5408,"Chute inversée");
INSERT INTO activite VALUES (5409,"Chute assis");
INSERT INTO activite VALUES (5410,"Ascensionnel");
INSERT INTO activite VALUES (5501,"Pêche au coup en eau douce");
INSERT INTO activite VALUES (5601,"Pêche en mer");
INSERT INTO activite VALUES (5701,"Pêche sportive à la mouche et au lancer");
INSERT INTO activite VALUES (5801,"Pentathlon Moderne");
INSERT INTO activite VALUES (5901,"Cesta punta/Mains nues/Pala/Chistera (grande, joko garbi)/Paleta/Xare/Frontenis/Pala corta/Rebot");
INSERT INTO activite VALUES (6001,"Pétanque et jeu provencal");
INSERT INTO activite VALUES (6101,"Planeur ULM / Multiaxe / Pendulaire / Paramoteur / Motorisations auxiliaires / Autogire ");
INSERT INTO activite VALUES (6201,"Randonnée pédestre");
INSERT INTO activite VALUES (6301,"Patinage artistique et danse sur roulettes");
INSERT INTO activite VALUES (6302,"Patinage de course");
INSERT INTO activite VALUES (6303,"Roller acrobatique");
INSERT INTO activite VALUES (6304,"Hockey sur patins en ligne / Hockey sur patins");
INSERT INTO activite VALUES (6306,"Planche à roulettes (Skate)");
INSERT INTO activite VALUES (6401,"Rugby à 15 / Rugby à 7");
INSERT INTO activite VALUES (6501,"Rugby à 13 / Rugby à 7");
INSERT INTO activite VALUES (6601,"Boxe française savate ");
INSERT INTO activite VALUES (6602,"Canne");
INSERT INTO activite VALUES (6603,"Bâton");
INSERT INTO activite VALUES (6604,"Savate défense");
INSERT INTO activite VALUES (6701,"Sauvetage en eau plate");
INSERT INTO activite VALUES (6702,"Sauvetage côtier/Surfboat");
INSERT INTO activite VALUES (6801,"Ski alpin (de piste)");
INSERT INTO activite VALUES (6802,"Ski nordique (de fond)");
INSERT INTO activite VALUES (6803,"Ski nordique-saut");
INSERT INTO activite VALUES (6804,"Ski nordique-biathlon");
INSERT INTO activite VALUES (6805,"Ski artistique");
INSERT INTO activite VALUES (6806,"Ski artistique bosses");
INSERT INTO activite VALUES (6807,"Ski artistique sauts");
INSERT INTO activite VALUES (6808,"Surf des neiges (snowboard)");
INSERT INTO activite VALUES (6901,"Téléski nautique");
INSERT INTO activite VALUES (6902,"Ski nautique classique / Course / à figures libres / nupieds / Kneeboard / Wake-board");
INSERT INTO activite VALUES (7001,"Spéléologie");
INSERT INTO activite VALUES (7101,"Sport automobile");
INSERT INTO activite VALUES (7102,"Karting");
INSERT INTO activite VALUES (7103,"Modélisme automobile radio-guidé");
INSERT INTO activite VALUES (7203,"Sports boules");
INSERT INTO activite VALUES (7204,"Boules traditionnelles");
INSERT INTO activite VALUES (7301,"Ballet sur glace / Danse sur glace / Patinage artistique ");
INSERT INTO activite VALUES (7302,"Bobsleigh");
INSERT INTO activite VALUES (7303,"Curling");
INSERT INTO activite VALUES (7304,"Hockey sur glace / Ringuette");
INSERT INTO activite VALUES (7305,"Luge");
INSERT INTO activite VALUES (7306,"Patinage synchronisé");
INSERT INTO activite VALUES (7307,"Patinage de vitesse");
INSERT INTO activite VALUES (7401,"Ski pulka");
INSERT INTO activite VALUES (7402,"Traineau à chiens");
INSERT INTO activite VALUES (7403,"Cross canin (Cani-Cross , Cani VTT , Ski Joering Canin)");
INSERT INTO activite VALUES (7501,"Squash");
INSERT INTO activite VALUES (7601,"Surf");
INSERT INTO activite VALUES (7701,"Taekwondo / Hapkido / Tang-soo-do / Soo bahk do / Sin moo hapkido / Hapkido jin jung kwan");
INSERT INTO activite VALUES (7801,"Tai chi chuan / Chi gong");
INSERT INTO activite VALUES (7901,"Tennis");
INSERT INTO activite VALUES (8001,"Tennis de table");
INSERT INTO activite VALUES (8101,"Carabine (hors 300m) / Pistolet / Plateaux");
INSERT INTO activite VALUES (8102,"Cible Mobile / Carabine 300m");
INSERT INTO activite VALUES (8103,"Arbalète / Armes anciennes / Bench rest / Silhouettes métalliques / Tir sportif de vitesse");
INSERT INTO activite VALUES (8104,"Tir aux armes réglementaires");
INSERT INTO activite VALUES (8201,"Tir à l'arc");
INSERT INTO activite VALUES (8301,"Triathlon");
INSERT INTO activite VALUES (8302,"Duathlon");
INSERT INTO activite VALUES (8401,"Twirling bâton");
INSERT INTO activite VALUES (8501,"Planche à Voile");
INSERT INTO activite VALUES (8502,"Dériveur / Multicoques / Courses océaniques / au large / Voile modèle / traditionnelle /match racing");
INSERT INTO activite VALUES (8503,"Voile radio commandée");
INSERT INTO activite VALUES (8601,"Vol à voile");
INSERT INTO activite VALUES (8602,"Voltige en planeur");
INSERT INTO activite VALUES (8701,"Cerf volant");
INSERT INTO activite VALUES (8702,"Cerf volant de traction (glisse aérotractée) et kitesurf");
INSERT INTO activite VALUES (8703,"Deltaplane");
INSERT INTO activite VALUES (8704,"Parapente");
INSERT INTO activite VALUES (8801,"Volley-ball / Volley-ball de plage (beach-volley) / Green-Volley");
INSERT INTO activite VALUES (8901,"Activités de forme et de santé");
INSERT INTO activite VALUES (8903,"Escalade dans les arbres");
INSERT INTO activite VALUES (8904,"Saut à l'élastique");
INSERT INTO activite VALUES (8906,"Racquetball");
INSERT INTO activite VALUES (8907,"Escalade sur PAH");
INSERT INTO activite VALUES (8909,"Paintball");
INSERT INTO activite VALUES (8999,"Autres (Autres)");
INSERT INTO activite VALUES (9001,"UNSS");
INSERT INTO activite VALUES (9002,"Sport scolaire");
INSERT INTO activite VALUES (9401,"Double dutch");