insert into historique(activite,dateRecherche,lieuRecherche,numUtilisateur) values ("Musculation",'2017/03/17',"Champs-sur-Marne",2);
insert into historique(activite,dateRecherche,lieuRecherche,numUtilisateur) values ("Baseball",'2017/03/17',"Champs-sur-Marne",2);
insert into historique(activite,dateRecherche,lieuRecherche,numUtilisateur) values ("Football / Football en salle (Futsal)",'2017/03/17',"Champs-sur-Marne",2);
insert into historique(activite,dateRecherche,lieuRecherche,numUtilisateur) values ("Handball / Mini hand / Handball de plage",'2017/03/17',"Champs-sur-Marne",2);
insert into historique(activite,dateRecherche,lieuRecherche,numUtilisateur) values ("Golf",'2017/03/17',"Champs-sur-Marne",2);
insert into historique(activite,dateRecherche,lieuRecherche,numUtilisateur) values ("Gymnastique Artistique",'2017/03/17',"Champs-sur-Marne",2);
insert into historique(activite,dateRecherche,lieuRecherche,numUtilisateur) values ("Musculation",'2017/03/18',"Claye-Souilly",2);
insert into historique(activite,dateRecherche,lieuRecherche,numUtilisateur) values ("Baseball",'2017/03/18',"Claye-Souilly",2);
insert into historique(activite,dateRecherche,lieuRecherche,numUtilisateur) values ("Football / Football en salle (Futsal)",'2017/03/18',"Claye-Souilly",2);
insert into historique(activite,dateRecherche,lieuRecherche,numUtilisateur) values ("Handball / Mini hand / Handball de plage",'2017/03/18',"Claye-Souilly",2);
insert into historique(activite,dateRecherche,lieuRecherche,numUtilisateur) values ("Golf",'2017/03/18',"Claye-Souilly",2);
insert into historique(activite,dateRecherche,lieuRecherche,numUtilisateur) values ("Gymnastique Artistique",'2017/03/18',"Claye-Souilly",2);
insert into historique(activite,dateRecherche,lieuRecherche,numUtilisateur) values ("Musculation",'2017/03/18',"Émerainville",2);
insert into historique(activite,dateRecherche,lieuRecherche,numUtilisateur) values ("Baseball",'2017/03/18',"Émerainville",2);
insert into historique(activite,dateRecherche,lieuRecherche,numUtilisateur) values ("Football / Football en salle (Futsal)",'2017/03/19',"Émerainville",2);
insert into historique(activite,dateRecherche,lieuRecherche,numUtilisateur) values ("Handball / Mini hand / Handball de plage",'2017/03/20',"Émerainville",2);
insert into historique(activite,dateRecherche,lieuRecherche,numUtilisateur) values ("Golf",'2017/03/21',"Émerainville",2);
insert into historique(activite,dateRecherche,lieuRecherche,numUtilisateur) values ("Gymnastique Artistique",'2017/03/22',"Émerainville",2);
insert into historique(activite,dateRecherche,lieuRecherche,numUtilisateur) values ("Musculation",'2017/03/21',"Champs-sur-Marne",2);
insert into historique(activite,dateRecherche,lieuRecherche,numUtilisateur) values ("Baseball",'2017/03/21',"Champs-sur-Marne",2);
insert into historique(activite,dateRecherche,lieuRecherche,numUtilisateur) values ("Football / Football en salle (Futsal)",'2017/03/21',"Champs-sur-Marne",2);
insert into historique(activite,dateRecherche,lieuRecherche,numUtilisateur) values ("Handball / Mini hand / Handball de plage",'2017/03/21',"Champs-sur-Marne",2);
insert into historique(activite,dateRecherche,lieuRecherche,numUtilisateur) values ("Golf",'2017/03/21',"Champs-sur-Marne",2);
insert into historique(activite,dateRecherche,lieuRecherche,numUtilisateur) values ("Gymnastique Artistique",'2017/03/20',"Champs-sur-Marne",2);
insert into historique(activite,dateRecherche,lieuRecherche,numUtilisateur) values ("Musculation",'2017/03/20',"Champs-sur-Marne",2);
insert into historique(activite,dateRecherche,lieuRecherche,numUtilisateur) values ("Baseball",'2017/03/20',"Champs-sur-Marne",2);
insert into historique(activite,dateRecherche,lieuRecherche,numUtilisateur) values ("Football / Football en salle (Futsal)",'2017/03/20',"Champs-sur-Marne",2);
insert into historique(activite,dateRecherche,lieuRecherche,numUtilisateur) values ("Handball / Mini hand / Handball de plage",'2017/03/20',"Champs-sur-Marne",2);
insert into historique(activite,dateRecherche,lieuRecherche,numUtilisateur) values ("Golf",'2017/03/20',"Champs-sur-Marne",2);
insert into historique(activite,dateRecherche,lieuRecherche,numUtilisateur) values ("Gymnastique Artistique",'2017/03/20',"Champs-sur-Marne",2);
insert into historique(activite,dateRecherche,lieuRecherche,numUtilisateur) values ("Tennis",'2017/03/22',"Champs-sur-Marne",2);
insert into historique(activite,dateRecherche,lieuRecherche,numUtilisateur) values ("Musculation",'2017/03/22',"Champs-sur-Marne",2);
insert into historique(activite,dateRecherche,lieuRecherche,numUtilisateur) values ("Football / Football en salle (Futsal)",'2017/03/22',"Champs-sur-Marne",2);
